#!/bin/bash
# ==========================================================
# NTP Server Auto Installer for LXC (Proxmox)
# Supported OS:
#   - Rocky Linux 9 / 10
#   - Ubuntu 24.04
#
# Default Upstream: id.pool.ntp.org
# Timezone: Asia/Jakarta
#
# Copyright (c) 2026 @kangsigi.id
# ==========================================================

set -e

AUTHOR="@kangsigi.id"
DEFAULT_NTP_POOL="id.pool.ntp.org"
TIMEZONE="Asia/Jakarta"
README_FILE="/root/README-NTP-SERVER.txt"
PROFILE_SCRIPT="/etc/profile.d/ntp-info.sh"

echo "=============================================="
echo " NTP Server Auto Installer"
echo " Author  : $AUTHOR"
echo "=============================================="

# -----------------------------
# Check root
# -----------------------------
if [[ $EUID -ne 0 ]]; then
   echo "ERROR: Please run as root."
   exit 1
fi

# -----------------------------
# Detect OS
# -----------------------------
if [ ! -f /etc/os-release ]; then
    echo "ERROR: Cannot detect OS."
    exit 1
fi

source /etc/os-release

OS_ID=$ID
OS_VERSION=$VERSION_ID

SUPPORTED=false
SERVICE_NAME=""
PKG_INSTALL=""
FIREWALL_TYPE="none"

if [[ "$OS_ID" == "rocky" && ( "$OS_VERSION" == "9" || "$OS_VERSION" == "10" ) ]]; then
    SUPPORTED=true
    SERVICE_NAME="chronyd"
    PKG_INSTALL="dnf install -y chrony"
    FIREWALL_TYPE="firewalld"
elif [[ "$OS_ID" == "ubuntu" && "$OS_VERSION" == "24.04" ]]; then
    SUPPORTED=true
    SERVICE_NAME="chrony"
    PKG_INSTALL="apt update && apt install -y chrony"
    FIREWALL_TYPE="ufw"
fi

if [ "$SUPPORTED" != true ]; then
    echo "ERROR: Unsupported OS."
    echo "Supported:"
    echo "- Rocky Linux 9 / 10"
    echo "- Ubuntu 24.04"
    exit 1
fi

echo "Detected OS: $PRETTY_NAME"

# -----------------------------
# Set Timezone
# -----------------------------
echo "Setting timezone to $TIMEZONE..."
if command -v timedatectl >/dev/null 2>&1; then
    timedatectl set-timezone $TIMEZONE || true
else
    ln -sf /usr/share/zoneinfo/$TIMEZONE /etc/localtime
fi

# -----------------------------
# Install Chrony
# -----------------------------
echo "Installing chrony..."
eval $PKG_INSTALL || { echo "ERROR: Failed installing chrony"; exit 1; }

# -----------------------------
# Internet Check
# -----------------------------
echo "Checking internet connectivity..."
ONLINE=true
ping -c 2 8.8.8.8 >/dev/null 2>&1 || ONLINE=false

# -----------------------------
# Backup config
# -----------------------------
if [ -f /etc/chrony.conf ]; then
    cp /etc/chrony.conf /etc/chrony.conf.backup.$(date +%F-%H%M%S)
fi

# -----------------------------
# Generate chrony config
# -----------------------------
echo "Configuring chrony..."

cat > /etc/chrony.conf <<EOF
# ==================================================
# Chrony Configuration
# Generated by $AUTHOR
# ==================================================

server 0.$DEFAULT_NTP_POOL iburst
server 1.$DEFAULT_NTP_POOL iburst
server 2.$DEFAULT_NTP_POOL iburst
server 3.$DEFAULT_NTP_POOL iburst

allow 0.0.0.0/0
driftfile /var/lib/chrony/drift
rtcsync
makestep 1.0 3
logdir /var/log/chrony
EOF

if [ "$ONLINE" = false ]; then
    echo "local stratum 10" >> /etc/chrony.conf
    echo "WARNING: No internet detected. Local stratum enabled."
fi

# -----------------------------
# Enable & Start Service
# -----------------------------
echo "Starting NTP service..."
systemctl enable $SERVICE_NAME
if ! systemctl restart $SERVICE_NAME; then
    echo "ERROR: NTP service failed to start."
    echo "Possible cause: LXC unprivileged container."
    echo "Solution:"
    echo "- Set container as privileged"
    echo "- Or allow CAP_SYS_TIME"
    exit 1
fi

# -----------------------------
# Firewall Setup
# -----------------------------
echo "Configuring firewall..."

if [[ "$FIREWALL_TYPE" == "firewalld" ]] && systemctl is-active firewalld >/dev/null 2>&1; then
    firewall-cmd --permanent --add-service=ntp || true
    firewall-cmd --reload || true
elif [[ "$FIREWALL_TYPE" == "ufw" ]] && command -v ufw >/dev/null 2>&1; then
    ufw allow 123/udp || true
fi

# -----------------------------
# Get IP
# -----------------------------
SERVER_IP=$(hostname -I | awk '{print $1}')

# -----------------------------
# Create Login Info Script
# -----------------------------
cat > $PROFILE_SCRIPT <<'EOF'
#!/bin/bash
SERVICE="chronyd"
if systemctl list-units | grep -q chrony; then
    SERVICE="chrony"
fi

IP=$(hostname -I | awk '{print $1}')
STATUS=$(systemctl is-active $SERVICE)
SOURCE=$(chronyc sources 2>/dev/null | grep \* | awk '{print $2}')
TRACK=$(chronyc tracking 2>/dev/null | grep "Leap status")

echo "---------------------------------------------"
echo " NTP SERVER INFORMATION"
echo "---------------------------------------------"
echo " IP Address     : $IP"
echo " Service        : $SERVICE ($STATUS)"
echo " Upstream Pool  : id.pool.ntp.org"
echo " Active Source  : $SOURCE"
echo " $TRACK"
echo "---------------------------------------------"
EOF

chmod +x $PROFILE_SCRIPT

# -----------------------------
# Create README
# -----------------------------
cat > $README_FILE <<EOF
==================================================
NTP SERVER INSTALLATION SUMMARY
Author: $AUTHOR
==================================================

Server IP         : $SERVER_IP
OS                : $PRETTY_NAME
Service           : $SERVICE_NAME
Upstream Pool     : id.pool.ntp.org
Timezone          : $TIMEZONE
Config File       : /etc/chrony.conf

--------------------------------------------------
HOW TO CHANGE UPSTREAM SERVER
--------------------------------------------------

Edit:
nano /etc/chrony.conf

Replace:
server 0.id.pool.ntp.org iburst

Then restart:
systemctl restart $SERVICE_NAME

--------------------------------------------------
CHECK STATUS
--------------------------------------------------

systemctl status $SERVICE_NAME
chronyc sources
chronyc tracking

--------------------------------------------------
IF SERVICE FAILS IN LXC
--------------------------------------------------

Container may be unprivileged.
Solutions:
- Set container as privileged
- Allow CAP_SYS_TIME

==================================================
EOF

echo "=============================================="
echo " NTP Server installation completed successfully"
echo " IP Address : $SERVER_IP"
echo " Service    : $SERVICE_NAME (active)"
echo "=============================================="
