#!/bin/bash
# ==========================================================
# NTP Server Auto Installer for LXC (Proxmox)
#
# Supported OS:
#   - Rocky Linux 9.x
#   - Rocky Linux 10.x
#   - Ubuntu 24.04
#
# Features:
#   - Auto OS detection
#   - Chrony installation
#   - Internet auto-detect (fallback local stratum)
#   - Allow all IP (0.0.0.0/0)
#   - Firewall auto configuration (if available)
#   - Timezone Asia/Jakarta
#   - Dynamic login banner
#   - Auto README generation
#
# Copyright (c) 2026 @kangsigi.id
# License: MIT
# ==========================================================

set -e

AUTHOR="@kangsigi.id"
DEFAULT_NTP_POOL="id.pool.ntp.org"
TIMEZONE="Asia/Jakarta"
README_FILE="/root/README-NTP-SERVER.txt"
PROFILE_SCRIPT="/etc/profile.d/ntp-info.sh"

echo "=============================================="
echo " NTP Server Auto Installer"
echo " Author  : $AUTHOR"
echo "=============================================="

# ----------------------------------------------------------
# 1. Check Root Privilege
# ----------------------------------------------------------
if [[ $EUID -ne 0 ]]; then
   echo "ERROR: Please run this script as root."
   exit 1
fi

# ----------------------------------------------------------
# 2. Detect OS
# ----------------------------------------------------------
if [ ! -f /etc/os-release ]; then
    echo "ERROR: Cannot detect OS."
    exit 1
fi

source /etc/os-release

OS_ID=$ID
OS_VERSION_FULL=$VERSION_ID
OS_VERSION_MAJOR=$(echo "$VERSION_ID" | cut -d '.' -f1)

SUPPORTED=false
SERVICE_NAME=""
PKG_INSTALL=""
FIREWALL_TYPE="none"

if [[ "$OS_ID" == "rocky" && ( "$OS_VERSION_MAJOR" == "9" || "$OS_VERSION_MAJOR" == "10" ) ]]; then
    SUPPORTED=true
    SERVICE_NAME="chronyd"
    PKG_INSTALL="dnf install -y chrony"
    FIREWALL_TYPE="firewalld"
elif [[ "$OS_ID" == "ubuntu" && "$OS_VERSION_FULL" == "24.04" ]]; then
    SUPPORTED=true
    SERVICE_NAME="chrony"
    PKG_INSTALL="apt update && apt install -y chrony"
    FIREWALL_TYPE="ufw"
fi

if [ "$SUPPORTED" != true ]; then
    echo ""
    echo "ERROR: Unsupported OS."
    echo "Detected: $PRETTY_NAME ($VERSION_ID)"
    echo ""
    echo "Supported OS:"
    echo "- Rocky Linux 9.x"
    echo "- Rocky Linux 10.x"
    echo "- Ubuntu 24.04"
    exit 1
fi

echo "Detected OS: $PRETTY_NAME"

# ----------------------------------------------------------
# 3. Set Timezone
# ----------------------------------------------------------
echo "Setting timezone to $TIMEZONE..."
if command -v timedatectl >/dev/null 2>&1; then
    timedatectl set-timezone $TIMEZONE || true
else
    ln -sf /usr/share/zoneinfo/$TIMEZONE /etc/localtime
fi

# ----------------------------------------------------------
# 4. Install Chrony
# ----------------------------------------------------------
echo "Installing chrony..."
eval $PKG_INSTALL || { echo "ERROR: Failed installing chrony."; exit 1; }

# ----------------------------------------------------------
# 5. Check Internet Connectivity
# ----------------------------------------------------------
echo "Checking internet connectivity..."
ONLINE=true
ping -c 2 8.8.8.8 >/dev/null 2>&1 || ONLINE=false

# ----------------------------------------------------------
# 6. Backup Existing Config
# ----------------------------------------------------------
if [ -f /etc/chrony.conf ]; then
    cp /etc/chrony.conf /etc/chrony.conf.backup.$(date +%F-%H%M%S)
fi

# ----------------------------------------------------------
# 7. Generate New Chrony Config
# ----------------------------------------------------------
echo "Generating chrony configuration..."

cat > /etc/chrony.conf <<EOF
# ==================================================
# Chrony Configuration
# Generated by $AUTHOR
# ==================================================

server 0.$DEFAULT_NTP_POOL iburst
server 1.$DEFAULT_NTP_POOL iburst
server 2.$DEFAULT_NTP_POOL iburst
server 3.$DEFAULT_NTP_POOL iburst

allow 0.0.0.0/0
driftfile /var/lib/chrony/drift
rtcsync
makestep 1.0 3
logdir /var/log/chrony
EOF

if [ "$ONLINE" = false ]; then
    echo "local stratum 10" >> /etc/chrony.conf
    echo "WARNING: Internet not detected. Local stratum enabled."
fi

# ----------------------------------------------------------
# 8. Enable & Start Service
# ----------------------------------------------------------
echo "Starting NTP service..."

systemctl enable $SERVICE_NAME

if ! systemctl restart $SERVICE_NAME; then
    echo ""
    echo "ERROR: Failed to start $SERVICE_NAME"
    echo "Possible cause: Unprivileged LXC container."
    echo "Solution:"
    echo "- Convert container to privileged"
    echo "- Or allow CAP_SYS_TIME capability"
    exit 1
fi

# ----------------------------------------------------------
# 9. Configure Firewall (If Available)
# ----------------------------------------------------------
echo "Configuring firewall..."

if [[ "$FIREWALL_TYPE" == "firewalld" ]] && systemctl is-active firewalld >/dev/null 2>&1; then
    firewall-cmd --permanent --add-service=ntp || true
    firewall-cmd --reload || true
elif [[ "$FIREWALL_TYPE" == "ufw" ]] && command -v ufw >/dev/null 2>&1; then
    ufw allow 123/udp || true
fi

# ----------------------------------------------------------
# 10. Create Dynamic Login Banner
# ----------------------------------------------------------
cat > $PROFILE_SCRIPT <<'EOF'
#!/bin/bash
SERVICE="chronyd"
if systemctl list-units | grep -q chrony.service; then
    SERVICE="chrony"
fi

IP=$(hostname -I | awk '{print $1}')
STATUS=$(systemctl is-active $SERVICE 2>/dev/null)
SOURCE=$(chronyc sources 2>/dev/null | grep \* | awk '{print $2}')
TRACK=$(chronyc tracking 2>/dev/null | grep "Leap status")

echo "---------------------------------------------"
echo "        NTP SERVER INFORMATION"
echo "---------------------------------------------"
echo " IP Address     : $IP"
echo " Service        : $SERVICE ($STATUS)"
echo " Upstream Pool  : id.pool.ntp.org"
echo " Active Source  : $SOURCE"
echo " $TRACK"
echo "---------------------------------------------"
EOF

chmod +x $PROFILE_SCRIPT

# ----------------------------------------------------------
# 11. Generate README File
# ----------------------------------------------------------
SERVER_IP=$(hostname -I | awk '{print $1}')

cat > $README_FILE <<EOF
==================================================
NTP SERVER INSTALLATION SUMMARY
Author: $AUTHOR
==================================================

Server IP         : $SERVER_IP
OS                : $PRETTY_NAME
Service           : $SERVICE_NAME
Upstream Pool     : id.pool.ntp.org
Timezone          : $TIMEZONE
Config File       : /etc/chrony.conf

--------------------------------------------------
HOW TO CHANGE UPSTREAM SERVER
--------------------------------------------------

Edit:
nano /etc/chrony.conf

Modify server lines and restart:

systemctl restart $SERVICE_NAME

--------------------------------------------------
CHECK STATUS
--------------------------------------------------

systemctl status $SERVICE_NAME
chronyc sources
chronyc tracking

--------------------------------------------------
LXC TROUBLESHOOTING
--------------------------------------------------

If you see:
Operation not permitted
Cannot adjust system clock

Your container is likely unprivileged.

Solutions:
- Convert container to privileged
- Allow CAP_SYS_TIME

==================================================
EOF

# ----------------------------------------------------------
# 12. Final Output
# ----------------------------------------------------------
echo ""
echo "=============================================="
echo " NTP Server Installation Completed"
echo " OS         : $PRETTY_NAME"
echo " IP Address : $SERVER_IP"
echo " Service    : $SERVICE_NAME (active)"
echo "=============================================="
