#!/bin/bash
# ==========================================================
# NTP Server Auto Installer (LXC Proxmox Ready)
# Version: v1.1
#
# Supported OS:
#   - Rocky Linux 9.x
#   - Rocky Linux 10.x
#   - Ubuntu 24.04
#
# Features:
#   - Colored output
#   - Versioning
#   - Auto container detection
#   - Rocky LXC auto fix (-x mode)
#   - Internet fallback
#   - Dynamic colored login banner
#
# Copyright (c) 2026 @kangsigi.id
# License: MIT
# ==========================================================

set -e

VERSION="v1.1"
AUTHOR="@kangsigi.id"
DEFAULT_NTP_POOL="id.pool.ntp.org"
TIMEZONE="Asia/Jakarta"
README_FILE="/root/README-NTP-SERVER.txt"
PROFILE_SCRIPT="/etc/profile.d/ntp-info.sh"

# ----------------------------------------------------------
# Color Definitions
# ----------------------------------------------------------
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m'

echo -e "${CYAN}==============================================${NC}"
echo -e "${GREEN} NTP Server Auto Installer ${VERSION}${NC}"
echo -e "${BLUE} Author  : ${AUTHOR}${NC}"
echo -e "${CYAN}==============================================${NC}"

# ----------------------------------------------------------
# Root Check
# ----------------------------------------------------------
if [[ $EUID -ne 0 ]]; then
   echo -e "${RED}ERROR: Run as root.${NC}"
   exit 1
fi

# ----------------------------------------------------------
# OS Detection
# ----------------------------------------------------------
source /etc/os-release
OS_ID=$ID
OS_VERSION_FULL=$VERSION_ID
OS_VERSION_MAJOR=$(echo "$VERSION_ID" | cut -d '.' -f1)

SUPPORTED=false
SERVICE_NAME=""
PKG_INSTALL=""
FIREWALL_TYPE="none"

if [[ "$OS_ID" == "rocky" && ( "$OS_VERSION_MAJOR" == "9" || "$OS_VERSION_MAJOR" == "10" ) ]]; then
    SUPPORTED=true
    SERVICE_NAME="chronyd"
    PKG_INSTALL="dnf install -y chrony"
    FIREWALL_TYPE="firewalld"
elif [[ "$OS_ID" == "ubuntu" && "$OS_VERSION_FULL" == "24.04" ]]; then
    SUPPORTED=true
    SERVICE_NAME="chrony"
    PKG_INSTALL="apt update && apt install -y chrony"
    FIREWALL_TYPE="ufw"
fi

if [ "$SUPPORTED" != true ]; then
    echo -e "${RED}ERROR: Unsupported OS ($PRETTY_NAME)${NC}"
    exit 1
fi

echo -e "${GREEN}Detected OS:${NC} $PRETTY_NAME"

# ----------------------------------------------------------
# Container Detection
# ----------------------------------------------------------
CONTAINER_MODE=false
if systemd-detect-virt -q; then
    CONTAINER_MODE=true
    echo -e "${YELLOW}Container detected: $(systemd-detect-virt)${NC}"
fi

# ----------------------------------------------------------
# Timezone
# ----------------------------------------------------------
echo -e "${CYAN}Setting timezone → ${TIMEZONE}${NC}"
timedatectl set-timezone $TIMEZONE 2>/dev/null || \
ln -sf /usr/share/zoneinfo/$TIMEZONE /etc/localtime

# ----------------------------------------------------------
# Install Chrony
# ----------------------------------------------------------
echo -e "${CYAN}Installing chrony...${NC}"
eval $PKG_INSTALL

# ----------------------------------------------------------
# Internet Check
# ----------------------------------------------------------
ONLINE=true
ping -c 2 8.8.8.8 >/dev/null 2>&1 || ONLINE=false

# ----------------------------------------------------------
# Config Generate
# ----------------------------------------------------------
[ -f /etc/chrony.conf ] && \
cp /etc/chrony.conf /etc/chrony.conf.backup.$(date +%F-%H%M%S)

cat > /etc/chrony.conf <<EOF
# Generated by $AUTHOR ($VERSION)

server 0.$DEFAULT_NTP_POOL iburst
server 1.$DEFAULT_NTP_POOL iburst
server 2.$DEFAULT_NTP_POOL iburst
server 3.$DEFAULT_NTP_POOL iburst

allow 0.0.0.0/0
driftfile /var/lib/chrony/drift
rtcsync
makestep 1.0 3
logdir /var/log/chrony
EOF

if [ "$ONLINE" = false ]; then
    echo "local stratum 10" >> /etc/chrony.conf
    echo -e "${YELLOW}No internet detected → Local stratum enabled.${NC}"
fi

# ----------------------------------------------------------
# Rocky LXC Fix
# ----------------------------------------------------------
if [[ "$OS_ID" == "rocky" && "$CONTAINER_MODE" == true ]]; then
    echo -e "${YELLOW}Applying Rocky LXC fix (-x mode)...${NC}"

    mkdir -p /etc/systemd/system/chronyd.service.d

    cat > /etc/systemd/system/chronyd.service.d/override.conf <<EOF
[Unit]
ConditionCapability=

[Service]
ExecStart=
ExecStart=/usr/sbin/chronyd -x
EOF
fi

# ----------------------------------------------------------
# Start Service
# ----------------------------------------------------------
systemctl daemon-reload
systemctl enable $SERVICE_NAME

if systemctl restart $SERVICE_NAME; then
    echo -e "${GREEN}NTP service started successfully.${NC}"
else
    echo -e "${RED}ERROR: Failed to start $SERVICE_NAME${NC}"
    exit 1
fi

# ----------------------------------------------------------
# Firewall
# ----------------------------------------------------------
if [[ "$FIREWALL_TYPE" == "firewalld" ]] && systemctl is-active firewalld >/dev/null 2>&1; then
    firewall-cmd --permanent --add-service=ntp || true
    firewall-cmd --reload || true
elif [[ "$FIREWALL_TYPE" == "ufw" ]] && command -v ufw >/dev/null 2>&1; then
    ufw allow 123/udp || true
fi

# ----------------------------------------------------------
# Colored Login Banner
# ----------------------------------------------------------
cat > $PROFILE_SCRIPT <<'EOF'
#!/bin/bash
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m'

SERVICE="chronyd"
if systemctl list-units | grep -q chrony.service; then
    SERVICE="chrony"
fi

IP=$(hostname -I | awk '{print $1}')
STATUS=$(systemctl is-active $SERVICE 2>/dev/null)
SOURCE=$(chronyc sources 2>/dev/null | grep \* | awk '{print $2}')

echo -e "${CYAN}---------------------------------------------${NC}"
echo -e "${GREEN}        NTP SERVER INFORMATION${NC}"
echo -e "${CYAN}---------------------------------------------${NC}"
echo -e "${BLUE} IP Address     :${NC} $IP"
echo -e "${BLUE} Service        :${NC} $SERVICE (${GREEN}$STATUS${NC})"
echo -e "${BLUE} Upstream Pool  :${NC} id.pool.ntp.org"
echo -e "${BLUE} Active Source  :${NC} $SOURCE"
echo -e "${CYAN}---------------------------------------------${NC}"
EOF

chmod +x $PROFILE_SCRIPT

# ----------------------------------------------------------
# README
# ----------------------------------------------------------
SERVER_IP=$(hostname -I | awk '{print $1}')

cat > $README_FILE <<EOF
NTP SERVER INSTALLATION SUMMARY
Version: $VERSION
Author : $AUTHOR

Server IP       : $SERVER_IP
OS              : $PRETTY_NAME
Container Mode  : $CONTAINER_MODE
Upstream        : id.pool.ntp.org
Timezone        : $TIMEZONE

Rocky LXC mode uses -x automatically.

Check:
systemctl status $SERVICE_NAME
chronyc sources
chronyc tracking
EOF

echo -e "${CYAN}==============================================${NC}"
echo -e "${GREEN} Installation Completed Successfully ${NC}"
echo -e "${BLUE} IP Address :${NC} $SERVER_IP"
echo -e "${BLUE} Service    :${NC} $SERVICE_NAME (running)"
echo -e "${CYAN}==============================================${NC}"
